# Site settings
baseurl = "http://navarroimmigration.com/"
languageCode = "en-us"
title = "Nadine Navarro"
theme = "hugo-artists-theme"
canonifurls = true
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

[params]
	name = "Nadine Navarro"
	description = "Immigration blog of Nadine Navarro for Miami Immigration. "
	email = "navarroimmigration@gmail.com"

	[params.header]
		title = "Navarro Immigration"
		shortBio = "Trusted // Honest // Experienced"


	# About section
	[params.about]
		title = "About me"
		bio = "**_Nadine Navarro_** received law degree from the _Florida State University College of Law_, where she completed courses in *Immigration and Asylum and Refugee Law*. She comes from an immigrant family and is a **passionate** immigrant advocate. You can **trust** Nadine for **honest** and **zealous representation**. You may contact Nadine with any immigration question or concerns."

		[[params.about.skills]]
			name = "Visitor Visas"
			value = 10

		[[params.about.skills]]
			name = "Family Petitions"
			value = 10

		[[params.about.skills]]
			name = "Naturalization"
			value = 10

		[[params.about.skills]]
			name = "Asylum"
			value = 10

		[[params.about.skills]]
			name = "Fiance Petitions"
			value = 10

		[[params.about.skills]]
			name = "Cuban Adjustment"
			value = 10

		[[params.about.skills]]
			name = "Extraordinary Ability Visas"
			value = 8

		[[params.about.skills]]
			name = "Adjusment of Status"
			value = 8

	# Contact section
	[params.contact]
		title = "Contact"

    # Social Media section
    [[params.social]]
        name = "facebook"
        link = "http://facebook.com/attorneynadinenavarro"

    [[params.social]]
        name = "skype"
        link = "skype:nadinenavarro5?call"

    [[params.social]]
        name = "google-plus"
        link = "http://plus.google.com/u/0/+nadinenavarro"

    [[params.social]]
        name = "linkedin"
        link = "http://www.linkedin.com/in/nadinenavarro"

    #Avvo
    [params.avvo]
        name = "avvo"
        link = "http://www.avvo.com/attorneys/nadine-navarro-4722436.html"

	[params.form]
		title = "Let's work together"
		# Form fields
		name = "Your Name"
		email = "Your Email"
		message = "Tell me about your immigration concerns"
		buttonText = "Send"


	[params.footer]
		copyright = "Navarro Immigration"